[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.28'
evm_version = 'cancun'
optimizer = true
optimizer-runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
